# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hopsa',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/hopsa',
                'lib_path': 'hop'},
  'syms': { 'hop.core': {'hop.core.foo': ('file_utils.html#foo', 'hop/core.py')},
            'hop.nb_utils': { 'hop.nb_utils._escape_table_cell': ('nb_utils.html#_escape_table_cell', 'hop/nb_utils.py'),
                              'hop.nb_utils._format_type': ('nb_utils.html#_format_type', 'hop/nb_utils.py'),
                              'hop.nb_utils.pydantic_to_markdown_table': ('nb_utils.html#pydantic_to_markdown_table', 'hop/nb_utils.py')},
            'hop.nbs': { 'hop.nbs._escape_table_cell': ('nbs.html#_escape_table_cell', 'hop/nbs.py'),
                         'hop.nbs._format_type': ('nbs.html#_format_type', 'hop/nbs.py'),
                         'hop.nbs.export_ipynb_toml': ('nbs.html#export_ipynb_toml', 'hop/nbs.py'),
                         'hop.nbs.export_ipynb_yaml': ('nbs.html#export_ipynb_yaml', 'hop/nbs.py'),
                         'hop.nbs.print_dict_structure': ('nbs.html#print_dict_structure', 'hop/nbs.py'),
                         'hop.nbs.pydantic_to_markdown_table': ('nbs.html#pydantic_to_markdown_table', 'hop/nbs.py')},
            'hop.ossys': {'hop.ossys.get_project_root': ('ossys.html#get_project_root', 'hop/ossys.py')}}}
