# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/hop',
                'doc_host': 'https://Hopsakee.github.io',
                'git_url': 'https://github.com/Hopsakee/hop',
                'lib_path': 'hop'},
  'syms': {'hop.core': {'hop.core.foo': ('core.html#foo', 'hop/core.py')}}}
